jwt:
  secret: mySecretKey
  expiration: 3600

spring:
  profiles:
    include: local
  datasource:
    url: jdbc:mysql://localhost:3306/wedide  # 로컬 테스트 진행을 위한 주소
    username: root
    password: Fpdlqms020@
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
