version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deployment
permissions:
  - object: /home/ubuntu/deployment
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: stop.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ubuntu
