name: Deploy to S3 and Trigger CodeDeploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      S3_BUCKET: webide-backend
      AWS_REGION: ap-northeast-2
      CODEDEPLOY_APPLICATION: webide-codedeploy
      CODEDEPLOY_GROUP: webide-backend-deploy

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew

      # Gradle build (Test 제외)
      - name: Build with Gradle
        run: |
          cd backend
          ./gradlew clean build -x test

      # 압축 파일 만들기
      - name: Make Zip File
        run: |
          zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      # AWS 인증
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $AWS_REGION

      - name: Upload artifact to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp ~/$GITHUB_SHA.jar s3://$S3_BUCKET/ --region $AWS_REGION

      - name: Trigger CodeDeploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
            --application-name $CODEDEPLOY_APPLICATION \
            --deployment-group-name $CODEDEPLOY_GROUP \
            --s3-location bucket=$S3_BUCKET,key=$GITHUB_SHA.jar,bundleType=zip \
            --region $AWS_REGION
