name: Deploy JAR to S3 and Trigger CodeDeploy
on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      S3_BUCKET: webide-backend
      AWS_REGION: ap-northeast-2
      CODEDEPLOY_APPLICATION: webide-codedeploy
      CODEDEPLOY_GROUP: webide-backend-deploy

    steps:
      # 프로젝트 체크아웃
      - uses: actions/checkout@v2

      # JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Gradle 빌드
      - name: Build with Gradle
        run: |
          ./gradlew clean build -x test

      # 빌드된 JAR 파일 이름 확인 및 변경
      - name: Rename JAR file
        run: |
          JAR_FILE=$(ls build/libs/*.jar | head -n 1) # JAR 파일 경로 가져오기
          echo "Found JAR file: $JAR_FILE"
          mv "$JAR_FILE" "./$GITHUB_SHA.jar"         # GITHUB_SHA 기반 이름 변경
          echo "Renamed to $GITHUB_SHA.jar"

      # AWS 인증
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # JAR 파일 S3 업로드
      - name: Upload JAR to S3
        run: |
          aws s3 cp "./$GITHUB_SHA.jar" s3://$S3_BUCKET/ --region $AWS_REGION

      # CodeDeploy 트리거
      - name: Trigger CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name $CODEDEPLOY_APPLICATION \
            --deployment-group-name $CODEDEPLOY_GROUP \
            --s3-location bucket=$S3_BUCKET,key=$GITHUB_SHA.jar,bundleType=zip \
            --region $AWS_REGION
